seed: 1265

model_params:
  #segment_length: 10
  h_dim: 128
  lr: 0.0000005
  nhead: 4
  token_dim: 128
  dropout: 0.2
  nEncoders: 1
  encoder: "ast"
  n_classes: 2

data_params:
  data_path: ["/media/fast_drive/audio_data_aligned/Session_5242023"] 
  radius: 6
  segment_length: 10
  transform: "ast"

dataloader_params:
  batch_size: 16
  num_workers: 6

trainer_params:
  max_epochs: 10
  accelerator: "gpu"
  devices: 1

logging_params:
  save_dir: "logger_runs/logs/"
  name: "ast"
  manifest_path: "logger_runs/manifest"